### ISSUE TITLE
Docker build not working

### ISSUE THREAD

**Issue by nr23730** [mig-frankfurt/dataelementhub.gui#45]
**Describe your problem.**

Using docker the build fails cause it required python.

**If it is a bug name steps to reproduce**

1. Clone repo
2. Run `docker build Dockerfile.dev`

**If it is a bug complete the following information:**

- Version: ab2abb99ceacb72ee0a622b051c92c4a63ab6765
- OS: macOS 12.3, Docker 20.10.12

**Additional context**

Docker error log:
```
 => ERROR [6/6] RUN npm install && npm audit fix && npm run build                                                                                                                               91.4s
------                                                                                                                                                                                                
 > [6/6] RUN npm install && npm audit fix && npm run build:                                                                                                                                           
#8 2.459 npm WARN old lockfile                                                                                                                                                                        
#8 2.459 npm WARN old lockfile The package-lock.json file was created with an old version of npm,                                                                                                     
#8 2.459 npm WARN old lockfile so supplemental metadata must be fetched from the registry.                                                                                                            
#8 2.460 npm WARN old lockfile                                                                                                                                                                        
#8 2.460 npm WARN old lockfile This is a one-time fix-up, please be patient...
#8 2.461 npm WARN old lockfile 
#8 48.92 npm WARN deprecated ufo@0.6.11: security: please use latest version
#8 50.18 npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
#8 50.58 npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
#8 50.96 npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
#8 51.58 npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
#8 51.73 npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
#8 52.68 npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
#8 53.01 npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
#8 57.74 npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
#8 59.20 npm WARN deprecated har-validator@5.1.5: this library is no longer supported
#8 59.89 npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
#8 61.00 npm WARN deprecated nuxt-i18n@6.26.0: Please use the @nuxtjs/i18n package going forward
#8 64.82 npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
#8 65.51 npm WARN deprecated @stylelint/postcss-markdown@0.36.2: Use the original unforked package instead: postcss-markdown
#8 65.80 npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
#8 71.72 npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
#8 84.44 npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
#8 84.45 npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
#8 84.46 npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
#8 84.48 npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
#8 84.49 npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
#8 90.85 npm notice 
#8 90.85 npm notice New patch version of npm available! 8.5.0 -> 8.5.5
#8 90.85 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.5>
#8 90.85 npm notice Run `npm install -g npm@8.5.5` to update!
#8 90.85 npm notice 
#8 90.85 npm ERR! code 1
#8 90.85 npm ERR! path /usr/src/dehub-gui/node_modules/fibers
#8 90.85 npm ERR! command failed
#8 90.85 npm ERR! command sh -c node build.js || nodejs build.js
#8 90.85 npm ERR! gyp info it worked if it ends with ok
#8 90.85 npm ERR! gyp info using node-gyp@8.4.1
#8 90.86 npm ERR! gyp info using node@16.14.2 | linux | x64
#8 90.86 npm ERR! gyp ERR! find Python 
#8 90.86 npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
#8 90.86 npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
#8 90.86 npm ERR! gyp ERR! find Python checking if "python3" can be used
#8 90.86 npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
#8 90.86 npm ERR! gyp ERR! find Python checking if "python" can be used
#8 90.86 npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
#8 90.86 npm ERR! gyp ERR! find Python 
#8 90.86 npm ERR! gyp ERR! find Python **********************************************************
#8 90.86 npm ERR! gyp ERR! find Python You need to install the latest version of Python.
#8 90.86 npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#8 90.86 npm ERR! gyp ERR! find Python you can try one of the following options:
#8 90.86 npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#8 90.86 npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
#8 90.86 npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
#8 90.86 npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
#8 90.86 npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#8 90.86 npm ERR! gyp ERR! find Python For more information consult the documentation at:
#8 90.86 npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#8 90.86 npm ERR! gyp ERR! find Python **********************************************************
#8 90.86 npm ERR! gyp ERR! find Python 
#8 90.86 npm ERR! gyp ERR! configure error 
#8 90.86 npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
#8 90.86 npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#8 90.86 npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#8 90.86 npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#8 90.86 npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#8 90.86 npm ERR! gyp ERR! stack     at exithandler (node:child_process:406:5)
#8 90.86 npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
#8 90.86 npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
#8 90.86 npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
#8 90.86 npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
#8 90.86 npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#8 90.86 npm ERR! gyp ERR! System Linux 5.10.76-linuxkit
#8 90.86 npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
#8 90.86 npm ERR! gyp ERR! cwd /usr/src/dehub-gui/node_modules/fibers
#8 90.86 npm ERR! gyp ERR! node -v v16.14.2
#8 90.86 npm ERR! gyp ERR! node-gyp -v v8.4.1
#8 90.86 npm ERR! gyp ERR! not ok 
#8 90.86 npm ERR! node-gyp exited with code: 1
#8 90.86 npm ERR! Please make sure you are using a supported platform and node version. If you
#8 90.86 npm ERR! would like to compile fibers on this machine please make sure you have setup your
#8 90.86 npm ERR! build environment--
#8 90.86 npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
#8 90.86 npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
#8 90.86 npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
#8 90.86 npm ERR! Alpine users please run: `sudo apk add python make g++`
#8 90.86 npm ERR! gyp info it worked if it ends with ok
#8 90.86 npm ERR! gyp info using node-gyp@8.4.1
#8 90.86 npm ERR! gyp info using node@16.14.2 | linux | x64
#8 90.86 npm ERR! gyp ERR! find Python 
#8 90.86 npm ERR! gyp ERR! find Python Python is not set from command line or npm configuration
#8 90.86 npm ERR! gyp ERR! find Python Python is not set from environment variable PYTHON
#8 90.86 npm ERR! gyp ERR! find Python checking if "python3" can be used
#8 90.86 npm ERR! gyp ERR! find Python - "python3" is not in PATH or produced an error
#8 90.86 npm ERR! gyp ERR! find Python checking if "python" can be used
#8 90.86 npm ERR! gyp ERR! find Python - "python" is not in PATH or produced an error
#8 90.86 npm ERR! gyp ERR! find Python 
#8 90.86 npm ERR! gyp ERR! find Python **********************************************************
#8 90.86 npm ERR! gyp ERR! find Python You need to install the latest version of Python.
#8 90.86 npm ERR! gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#8 90.86 npm ERR! gyp ERR! find Python you can try one of the following options:
#8 90.86 npm ERR! gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#8 90.86 npm ERR! gyp ERR! find Python   (accepted by both node-gyp and npm)
#8 90.86 npm ERR! gyp ERR! find Python - Set the environment variable PYTHON
#8 90.86 npm ERR! gyp ERR! find Python - Set the npm configuration variable python:
#8 90.86 npm ERR! gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#8 90.86 npm ERR! gyp ERR! find Python For more information consult the documentation at:
#8 90.87 npm ERR! gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#8 90.87 npm ERR! gyp ERR! find Python **********************************************************
#8 90.87 npm ERR! gyp ERR! find Python 
#8 90.87 npm ERR! gyp ERR! configure error 
#8 90.87 npm ERR! gyp ERR! stack Error: Could not find any Python installation to use
#8 90.87 npm ERR! gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:330:47)
#8 90.87 npm ERR! gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:159:21)
#8 90.87 npm ERR! gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:202:16)
#8 90.87 npm ERR! gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:294:16)
#8 90.87 npm ERR! gyp ERR! stack     at exithandler (node:child_process:406:5)
#8 90.87 npm ERR! gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
#8 90.87 npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:526:28)
#8 90.87 npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
#8 90.87 npm ERR! gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
#8 90.87 npm ERR! gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#8 90.87 npm ERR! gyp ERR! System Linux 5.10.76-linuxkit
#8 90.87 npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
#8 90.87 npm ERR! gyp ERR! cwd /usr/src/dehub-gui/node_modules/fibers
#8 90.87 npm ERR! gyp ERR! node -v v16.14.2
#8 90.87 npm ERR! gyp ERR! node-gyp -v v8.4.1
#8 90.87 npm ERR! gyp ERR! not ok 
#8 90.87 npm ERR! node-gyp exited with code: 1
#8 90.87 npm ERR! Please make sure you are using a supported platform and node version. If you
#8 90.87 npm ERR! would like to compile fibers on this machine please make sure you have setup your
#8 90.87 npm ERR! build environment--
#8 90.87 npm ERR! Windows + OS X instructions here: https://github.com/nodejs/node-gyp
#8 90.87 npm ERR! Ubuntu users please run: `sudo apt-get install g++ build-essential`
#8 90.87 npm ERR! RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'` 
#8 90.87 npm ERR! Alpine users please run: `sudo apk add python make g++`
#8 90.88 
#8 90.88 npm ERR! A complete log of this run can be found in:
#8 90.88 npm ERR!     /root/.npm/_logs/2022-03-24T13_47_55_818Z-debug-0.log
------
executor failed running [/bin/sh -c npm install && npm audit fix && npm run build]: exit code: 1
ERROR: Service 'dehub-gui' failed to build : Build failed
```

**Comment by ammarbarakat** [comment]
@nr23730 Unfortunately I could not replicate the bug. 
Please try it again but this time after defining all required ENV Variables (they are not included in Dockerfile.dev):
ENV DIR
ENV KEYCLOAK_REALM
ENV KEYCLOAK_URL
ENV BASE_URL
ENV MDR_BACKEND_URL

If it does not work after making these changes, please contact us again.

**Comment by nr23730** [comment]
This issue still persists.

I also tried building the `develop` and the `47_Design_makeover` branches. Neither of them worked.
