### ISSUE TITLE
Version mismatch in vue packages

### ISSUE THREAD

**Issue by nr23730** [mig-frankfurt/dataelementhub.gui#51]
**Describe your problem.**

There seems to be a version mismatch in vue packages, so that the build cannot be completed successfully.

**If it is a bug name steps to reproduce**

1. Clone git repo
2. Checkout branch `develop`
3. Build using Docker

**Describe the solution you'd like**

Version mismatch resolved. 

**Additional context**

I was able to build the image by replacing npm with yarn...

Error log:
```
#10 66.12 > dataelementhub@1.0.0 build
#10 66.12 > nuxt build
#10 66.12 
#10 66.80 
#10 66.80  FATAL 
#10 66.80 
#10 66.80 Vue packages version mismatch:
#10 66.80 
#10 66.80 - vue@2.6.12
#10 66.80 - vue-server-renderer@2.6.14
#10 66.80 
#10 66.80 This may cause things to work incorrectly. Make sure to use the same version for both.
#10 66.80 
#10 66.80 
#10 66.80   
#10 66.80   Vue packages version mismatch:
#10 66.80   
#10 66.80   - vue@2.6.12
#10 66.80   - vue-server-renderer@2.6.14
#10 66.80   
#10 66.80   This may cause things to work incorrectly. Make sure to use the same version for both.
#10 66.80   
#10 66.80   at Object.<anonymous> (node_modules/vue-server-renderer/index.js:8:9)
#10 66.80   at Module._compile (node:internal/modules/cjs/loader:1105:14)
#10 66.80   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
#10 66.80   at Module.load (node:internal/modules/cjs/loader:981:32)
#10 66.80   at Function.Module._load (node:internal/modules/cjs/loader:822:12)
#10 66.80   at Module.require (node:internal/modules/cjs/loader:1005:19)
#10 66.80   at require (node:internal/modules/cjs/helpers:102:18)
#10 66.80   at Object.<anonymous> (node_modules/@nuxt/vue-renderer/dist/vue-renderer.js:19:27)
#10 66.80   at Module._compile (node:internal/modules/cjs/loader:1105:14)
#10 66.80   at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
#10 66.80 
#10 66.81 
#10 66.81 ╭──────────────────────────────────────────────────────────────────────────────╮│                                                                              ││   ✖ Nuxt Fatal Error                                                         ││                                                                              ││   Error:                                                                     ││                                                                              ││   Vue packages version mismatch:                                             ││                                                                              ││   - vue@2.6.12                                                               ││   - vue-server-renderer@2.6.14                                               ││                                                                              ││   This may cause things to work incorrectly. Make sure to use the same       ││   version for                                                                ││   both.                                                                      ││                                                                              ││                                                                              │╰──────────────────────────────────────────────────────────────────────────────╯
#10 66.81 
```

**Comment by ammarbarakat** [comment]
Both issues [#51](https://github.com/mig-frankfurt/dataelementhub.gui/issues/51) & [#50](https://github.com/mig-frankfurt/dataelementhub.gui/issues/50) will be solved by filling out the env variables in this Dockerfile and using it

```
FROM node:14-buster-slim
ENV DIR=/usr/src/dehub-gui
ENV KEYCLOAK_REALM=
ENV KEYCLOAK_URL=
ENV BASE_URL=
ENV MDR_BACKEND_URL=
RUN mkdir -p $DIR
WORKDIR $DIR
#RUN sed -i 's/https/http/' /etc/apk/repositories
#RUN apk update && apk upgrade && apk add git
RUN apt update && apt dist-upgrade
COPY . $DIR
RUN npm install && npm audit fix && npm run build
EXPOSE 3000
ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000
CMD [ "npm", "run", "start" ]
```

Docker command:

`docker build -t dehub-gui .`
